from math import *

print("Giraffe Academy")
print("Giraffe\nAcademy")
print("Giraffe\"Academy")
print("Giraffe\Academy")
phrase = "Giraffe Academy"
print(phrase)
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
# Indexing in Python starts with Zer0.
print(phrase[0])
print(phrase.index("a"))
print(phrase.index("Acad"))
# print(phrase.index("z"))
print(phrase.replace("Giraffe", "Elephant"))
print(2)
print(10 % 3)
my_num = -21
print(str(my_num) + " my faorite number")
print(abs(my_num))
print(pow(4, 2))
print(max(4, 2))
print(min(4, 2))
print(round(3.7))
print(floor(3.7))
print(sqrt(36))